# --- Main Database Config
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/melay
    username: postgres
    password: password

# --- Migrations ---
  flyway:
    url: jdbc:postgresql://localhost:5432/melay
    user: postgres
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
