server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:certs/node-1/node-1-keystore.p12    # add to resources or reference path
    key-store-password: 4490
    key-store-type: PKCS12
    trust-store: classpath:certs/node-1/trusted-ca.p12
    trust-store-password: 449090
    trust-store-type: PKCS12
    client-auth: want    # require client certificates (mTLS)
